### ISSUE TITLE
INonfungiblePositionManager cannot be compiled without optimization

### ISSUE THREAD

**Issue by ivanzhelyazkov** [Uniswap/uniswap-v3-periphery#106]
Attempting compilation of INonfungiblePositionManager with no optimization fails with:
`"CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.".`

This is probably caused by the **function positions(uint256 tokenId)** returning too many variables and accessing a slot in the stack that is deeper than its 16th element.

That is a problem for code testing contracts which use the position manager - the solidity coverage plugin tests all code by compiling without optimization, and including the INonfungiblePositionManager in another contract causes the compilation to fail.

Possible solutions are refactoring the **function positions(uint256 tokenId)** by returning it's variables in a struct, or splitting it in two different functions.

npm version:
"@uniswap/v3-periphery": "^1.0.0-beta.21"

**Comment by moodysalem** [comment]
You should deploy and test against the bytecode in the artifacts directory, rather than compile it locally for testing. This issue sounds like an issue with the tooling you're using, not the code in the repo

**Comment by ivanzhelyazkov** [comment]
Actually, the contract is used by another one, so it needs to be imported, from where the problem arises - The entire contract gets recompiled, including the import, and the compilation fails.

**Comment by moodysalem** [comment]
> Actually, the contract is used by another one, so it needs to be imported, from where the problem arises - The entire contract gets recompiled, including the import, and the compilation fails.

That is the approach of the tool that is checking the code coverage, you should be able to exclude external dependencies from coverage testing (or if you are trying to coverage test this repo, then you will need to work around the technical limitations of the approach with that tool)

**Comment by mshakeg** [comment]
Instead of having `positions` return all 12 primitive types having it return a struct containing all 12 types could possibly fix your issue?
