### ISSUE TITLE
Please do initialise some pairs and an early documentation release would be really helpful as well 

### ISSUE THREAD

**Issue by aak-dev** [Uniswap/uniswap-v3-periphery#107]
https://github.com/Uniswap/uniswap-v3-periphery/blob/main/testnet-deploys.md#kovan
The contracts on testnets have been redeployed 2 times and no documentation is to found.

**Comment by moodysalem** [comment]
Docs are currently being built out here
https://docs.uniswap.org/

**Comment by aak-dev** [comment]
With the launch on mainnet near wanted a deep dive on v3 functions to integrate with the dapp I am building. Hope it will be added soon.

**Comment by aak-dev** [comment]
And I am unable to add pairs on Kovan to test with.
