### ISSUE TITLE
Mint function in NonfungiblePositionManager token sorting

### ISSUE THREAD

**Issue by ivanzhelyazkov** [Uniswap/uniswap-v3-periphery#110]
After deploying a pool with two tokens token0/token1 using createAndInitializePoolIfNecessary, 
calling the mint function in NonfungiblePositionManager reverts without a message,
which is probably due to the token address ordering in mint function.
Calling the mint function with reversed addresses token1 : token0 results in transaction success, and mints the NFT.
Tested on Kovan.

Stack trace (Hardhat):
Error: Transaction reverted without a reason
    at NonfungiblePositionManager.computeAddress (contracts/libraries/PoolAddress.sol:34)
    at NonfungiblePositionManager.addLiquidity (contracts/base/LiquidityManagement.sol:63)
    at NonfungiblePositionManager.mint (contracts/NonfungiblePositionManager.sol:159)

**Comment by moodysalem** [comment]
We check the address order is token0, token1, because tickLower and tickUpper depend on knowing the order of the tokens, so it does not make sense to pass in unsorted tokens.

**Comment by ivanzhelyazkov** [comment]
The tokens passed to mint are sorted like the pool pair. Shouldn't they be passed the same way ?

**Comment by moodysalem** [comment]
Yes they should be passed in the sort order of the pool. Please include a transaction hash and I'll look into it, but what you're saying does not sound right (tokens passed in reverse sorting error should always revert)
