### ISSUE TITLE
change bottom left text

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-v3-periphery#120]
`Min:` -> `Min Tick:`
`Max:` -> `Max Tick:`

**Comment by ewilz** [comment]
addressed here: https://github.com/Uniswap/uniswap-v3-periphery/pull/117

**Comment by moodysalem** [comment]
we can also format prices which is probably better?

**Comment by ewilz** [comment]
@callil originally had this idea of showing more cryptic/hacky information on the card as an aesthetic. I think we moved away from that a little bit and maybe prices work too...I have no strong opinion
