### ISSUE TITLE
sweepTokenWithFee and unwrapWETH9WithFee unused?

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/uniswap-v3-periphery#121]
It seems these methods are costly alternatives to unwrapWETH9 and sweepToken but it is not clear why they are there. If they can be removed from SwapRouter, it would save gas on the 4byte lookup table.

**Comment by NoahZinsmeister** [comment]
they exist so that you can choose to redirect a portion of your output to a specified fee recipient without having to deploy a separate router, a benefit we've deemed worth the very small (potential) cost of increased lookup table costs
