### ISSUE TITLE
When I call position function in contract, the values returned are not the same as the nft position values in the uniswap interface. why is that?

### ISSUE THREAD

**Issue by descartes2100** [Uniswap/uniswap-v3-periphery#143]
Result {   
  '0': '0',
  '1': '0x0594E76D53C30E7Ff629cac03fd0FfF4eB5646bb',
  '2': '0xc778417E063141139Fce010982780140Aa0cD5Ab',
  '3': '0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735',
  '4': '10000',
  '5': '92000',
  '6': '94200',
  '7': '443075020326629924852',
  '8': '0',
  '9': '16315047476139088235697466691278572',
  '10': '419479519460959764',
  '11': '444989017688262209043',
  nonce: '0',
  operator: '0x0594E76D53C30E7Ff629cac03fd0FfF4eB5646bb',
  token0: '0xc778417E063141139Fce010982780140Aa0cD5Ab',
  token1: '0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735',
  fee: '10000',
  tickLower: '92000',
  tickUpper: '94200',
  liquidity: '443075020326629924852',
  feeGrowthInside0LastX128: '0',
  feeGrowthInside1LastX128: '16315047476139088235697466691278572',
  tokensOwed0: '419479519460959764',
  tokensOwed1: '444989017688262209043'
}

How should I interpret these values?

**Comment by moodysalem** [comment]
I added issue https://github.com/Uniswap/uniswap-v3-periphery/issues/144 to create a library for this math

**Comment by aranair** [comment]
@moodysalem is it possible to derive `tokensOwed0` externally? Like, from `feeGrowthInside0LastX128` and `liquidity`, something like `mulDiv(feeGrowthInside0LastX128, liquidity, Q128)`?
