### ISSUE TITLE
 We want to access NFT amount information through the router.

### ISSUE THREAD

**Issue by montaigne2142** [Uniswap/uniswap-v3-periphery#145]
Hello friends, we are building a dapp that we will use uniswap. We want to reach the current state of the token 0 and token 1 values of the NFT positions we hold.? We need to know how much fee the position is currently accumulating.? We want to access this information through the router. Our aim is to settle transactions with a contract.We created an issues on github, we did research on the documentation, we asked it on discord before.We're trying to build on Uniswap and we really need someone's support. Please can someone help us?

**Comment by moodysalem** [comment]
That is exactly this issue
https://github.com/Uniswap/uniswap-v3-periphery/issues/144
