### ISSUE TITLE
Add `@openzeppelin/contracts@3.4.1-solc-0.7-2` contracts to be compiled into artifacts-ovm

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-v3-periphery#151]
We need `TransparentUpgradeableProxy` and `ProxyAdmin` on the optimism branch, to make sure that we can access the version compiled with the optimism compiler.

**Comment by moodysalem** [comment]
fixed for openzeppelin artifacts and multicall as of https://github.com/Uniswap/uniswap-v3-periphery/commit/85cc63c6ea867f406e10e5dd55e5c5bc53b29378
