### ISSUE TITLE
feeGrowthInside in Position.Info is negative

### ISSUE THREAD

**Issue by KimiWu123** [Uniswap/uniswap-v3-periphery#164]
We're building our own protocol on top of your protocol, and interact to `core` directly. Found that `feeGrowthInside0LastX128` in `Position.Info` is negative. Here is our scenario, 

0. fee tier is 1% and no any liquidity added
1. Alice `mint` at the tick range [50200, 50400]
2. Bob `swap` and the  tick is still at the range of [50200, 50400]
3. Alice `mint` at the different tick range [50000,  50200]
4. Bob `swap` and move the tick to the range [50000, 50200]
5. Call `pool.Position()`, the `feeGrowthInside0LastX128` is a negative value (like this ,`115792089237316195423570985008687907853269981933551626474612330109638790286637`)

Does a negative value fit your expectation? Or did we miss anything?

**Comment by NoahZinsmeister** [comment]
@KimiWu123 this is the wrong repo for this issue, as you're describing a behavior in core. however, it's not unexpected for `feeGrowthInside{0,1}LastX128` to overflow, these snapshot values are only meaningful in the context of `feeGrowthInside{0,1}X128` as calculated by [`getFeeGrowthInside`](https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/libraries/Tick.sol#L60), and the operations involving these values always result in non-overflowed results
