### ISSUE TITLE
Rounding issues and calculations

### ISSUE THREAD

**Issue by buckyass1** [Uniswap/uniswap-v3-periphery#167]
Hi, I am trying to build an dapp that uses uniswap but I have few questions about how you round numbers on liquidity part.

1) On add liquidity part, when I type "1" on your ui and check the transaction, I see a value like 0.99999999993454. I wonder why its not just "1"? And how can I achieve this behavior?
2) I am calculating amount1Desired with getAmountsForLiquidity() function from LiquidityMath.sol. When I type a big number (like 10 million) as amount0Desired on your ui, it keep adding zeros after six digit. I see a value like 2158840000 but when I calculate it, I find a value like 2158845277.6637. I also wonder why this is happening? Should I do the same thing?

Any help would be great, thank you.

**Comment by moodysalem** [comment]
position sdk has the code you need https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/entities/position.ts#L312-L342

**Comment by buckyass1** [comment]
But it asks me amount0 and amount1, how can I use it without knowing the amount1 value correctly?

**Comment by moodysalem** [comment]
you pass in amount0 and amount1 that you wish to contribute, and then position.amount0 and position.amount1 contain the actual amounts

e.g.:

```typescript
position.fromAmounts({amount0: 100, amount1: 200, ...}).amount0
```
