### ISSUE TITLE
limited approval

### ISSUE THREAD

**Issue by nonnanna** [Uniswap/uniswap-v3-periphery#174]
Let's say one has USDC and wants to swap some of it to some other token.

Referring to this Unlimited Approval Risk:

https://kalis.me/unlimited-erc20-allowances/

https://coinmarketcap.com/alexandria/glossary/infinite-approval

I don't want that. It is OK to approve uniswap multiple times and pay a fee for that very time or approve up to a custom limit. However due to smart contract risks I don't want unlimited approval.

Could you please add a limited approval feature?

**Comment by moodysalem** [comment]
We already use permit in the interface for USDC which is supported by the contracts via `SelfPermit`
