### ISSUE TITLE
Transaction fails with 'Not Weth9' error

### ISSUE THREAD

**Issue by buckyass1** [Uniswap/uniswap-v3-periphery#175]
Hi, I would like to ask you about 'Not Weth9' Error. (Here a failed transaction [https://ropsten.etherscan.io/tx/0xb71e40948fe57dd21ab233e12988d376d197f33fd9de0b45f5267cb89c65df45](url) ) I create data using nftManager.sol mint function. And set 'to' address to '0xC36442b4a4522E871399CD717aBDD847Ab11FE88' (nftManager.sol contract's address) Im sending transaction like this: 

`async function sendHashoriginal(_to, _data, _gaslimit) {
        const signer = getSigner(props.provider)
        const { hash } = await signer.sendTransaction({
            to: _to,
            value: 0,
            data: _data,
            gasLimit: _gaslimit,
        })
`
But my transactions keep failing with this 'not weth9' error. When I try the same data and stuff without sending it to metamask, (signing it automatically with my private key using web3.js) it works fine. Can you guys show me a lead? Im really stuck with this error.

**Comment by moodysalem** [comment]
The first 4 bytes of your data is not matching a function selector, and thus you are hitting the fallback function which should only ever happen when `WETH9#withdraw` is triggered
