### ISSUE TITLE
Incorrect amount returned from LiquidityAmounts

### ISSUE THREAD

**Issue by ryuheimat** [Uniswap/uniswap-v3-periphery#178]
I am using `LiquidityAmounts` library to get expected `amount0` and `amount1` to add liquidity.
But sometimes, `LiquidityAmounts` returned less amount than real amount used to add liquidity.

ex, I tried to test with USDT/DAI pair on mainnet fork.
`LiquidityAmounts` returns `10999999` USDT, but when I add liquidity through `NonfungiblePositionManager`, it use `11000000` USDT.

**Comment by moodysalem** [comment]
The `getAmountsForLiquidity` function returns the amount you would get if you burned that much liquidity. When adding liquidity, we must round the token amount up. When burning liquidity, we must round the token amount down.
