### ISSUE TITLE
How to get UNI-V3-POS on Rinkeby network?

### ISSUE THREAD

**Issue by williamjin127** [Uniswap/uniswap-v3-periphery#190]
Hello,
I can see lots of UNI-V3-POS transactions in rinkeby etherscan.
But I am not sure how they are getting the UNI-V3-POS in rinkeby network.
I know i can get it in mainnet by providing liquidity but how to do it in testnet?
Please help me.
Thanks!

**Comment by moodysalem** [comment]
You can use the interface on Rinkeby by connecting a wallet and switching networks in your wallet, then use Uniswap on the testnet.

**Comment by williamjin127** [comment]
Hi @moodysalem 
I tried so. Please look at the screenshot.
![Screenshot from 2021-08-19 13-57-23](https://user-images.githubusercontent.com/10380074/130120168-96a88337-d0cb-488b-93ec-0a25ae9e887e.png)
How to set starting price to initialize pool in Rinkeby network?

**Comment by moodysalem** [comment]
You are the first one to deposit to the pool so you decide it

**Comment by williamjin127** [comment]
So is it possible to test doing liquidity pool in Rinkeby network?
