### ISSUE TITLE
Function to convert address[] path to byte path

### ISSUE THREAD

**Issue by ceds** [Uniswap/uniswap-v3-periphery#195]
With V2 specifying path for functions was easy:

```
address[] path;
path[0] = address1;
path[1] = address2;
path[2] = address3;
```

However, with V3, path has to be a byte which consist of address as well as fees.  

Currently I have no idea how to construct the byte variable.  Is there documentation on this or a function that can assist ?

**Comment by moodysalem** [comment]
I believe it's `abi.encodePacked(address1, fee1_2, address2, fee2_3, address3)` in the exact input case, and the reverse in the exact output case

The JS examples are here https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/encodeRouteToPath.ts#L6-L39
and here https://github.com/Uniswap/uniswap-v3-periphery/blob/main/test/shared/path.ts

**Comment by Yorkemartin** [comment]
There is also a solidity example available in the docs https://docs.uniswap.org/protocol/guides/swaps/multihop-swaps#input-parameters-1
