### ISSUE TITLE
How to get the right price of currency pairs (e.g. BTC/USDT) from 3 different fee pools

### ISSUE THREAD

**Issue by ningyiyi0718** [Uniswap/uniswap-v3-periphery#196]
When I use the method {**getQuoteAtTick()** of OracleLibrary} to calculate the price of a currency pair, the pool  **slot0.sqrtPriceX96** or **slot0.tick** are also different, so I cannot get the same price of 3 pools, the price of BTC/USDT calculated is different but only one is right price maybe 3000 fee pool, other 2 pools price is not right.

So the question is **When I don’t know the price of BTC/USDT, how can I determine which of the 3 pools price is correct?**

e.g.: the **current price** BTC/USDT is 48000 USDT/BTC
45000 USDT/BTC I get the price of 500 fee pool by getQuoteAtTick() method.
48000 USDT/BTC I get the price of 3000 fee pool by getQuoteAtTick() method. (**right price**)
49000 USDT/BTC I get the price of 10000 fee pool by getQuoteAtTick() method.

If I don't know the **current price**, how do I know which pools price is right?

Is there a problem with my calculation OR Is there any other way to solve it？

thanks for everyone

**Comment by moodysalem** [comment]
You may consider using the weighted oracle library

https://github.com/Uniswap/uniswap-v3-periphery/blob/main/contracts/libraries/WeightedOracleLibrary.sol

**Comment by ningyiyi0718** [comment]
ok, thanks, I try
