### ISSUE TITLE
Oracle library

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-v3-periphery#22]
Need a library that returns TWAP for base currency/quote currency over some time period as a `FixedPoint128` number

Considerations
- how to choose between multiple pools
- other kinds of averages (EMA)

**Comment by leonardgee** [comment]
This will be quite useful, is there any update on this? Also where can we find the oracle implementation for Uniswap v3?

**Comment by alejoamiras** [comment]
Right now I think, althought the Oracle Library MVP is pretty cool, it's not procution / protocol integration ready. I'm trying to implement a programatical way of selecting the best pool, why not getting `!OLD` or being open to an attack, and couldn't find an easy anser (and don't have time to learn all the uni v3 codebase). I know in #96 @NoahZinsmeister talked about "aggregating over multiple fee tiers", is there an ETA on this ? 😭 
Great work, nonetheless.

**Comment by moodysalem** [comment]
We now have https://github.com/Uniswap/uniswap-v3-periphery/blob/b771ff9a20a0fd7c3233df0eb70d4fa084766cde/contracts/libraries/OracleLibrary.sol

I agree we could build something opinionated on how to weight ticks across fee levels
