### ISSUE TITLE
Reference Pool address 

### ISSUE THREAD

**Issue by Bernardchoo** [Uniswap/uniswap-v3-periphery#51]
Hi all , 

I according to the core and periphery contracts, there consist of 2 methods of getting the pool address. First is through the factory, another method is through computing the pool address.  

 
UniswapV3Factory.sol                     

                IUniswapV3Factory(factory).getPool(
                                  params.token0,
                                  params.token1,
                                  params.fee
                              )
   
--------------------------------
SwapRouter.sol

                PoolAddress.computeAddress(
                    factory,
                    PoolAddress.getPoolKey(tokenA, tokenB, fee))

--------------------------------
![compute address error](https://user-images.githubusercontent.com/19634427/112747686-89fad080-8fe9-11eb-9217-3909e2b82d78.JPG)

However , through my observsation that the return addresses for both are different. 

![123](https://user-images.githubusercontent.com/19634427/112747689-9121de80-8fe9-11eb-89c6-374a92768fca.JPG)

![image](https://user-images.githubusercontent.com/19634427/112748114-5a00fc80-8fec-11eb-9d1e-76b6dc0c7069.png)

I gently twited the function in swapRouter to public and return the computedAddress for debugging purpose to find out the return address from computeAddress.

I found out that the Pool address return from the Library PoolAddress,compute is not providing the same address as the function getPool in the Factory contract.  Therefore , the computeAddress in PoolAddress library is not usable ? 
The pool address return from the Factory contract is the actual pool address that contains the bytecode.
Maybe I am wrong. Looking forward to your reply.

Thank you.

**Comment by Bernardchoo** [comment]
![image](https://user-images.githubusercontent.com/19634427/112754726-f5579900-900f-11eb-872f-80a8da4f7925.png)

My test set up with sorted token and same fees.

**Comment by moodysalem** [comment]
Make sure you're using both the latest version of the `@uniswap/v3-core` and `@uniswap/v3-periphery` packages, as the init code hash from v3-core pool is hard coded in the v3-periphery package

**Comment by moodysalem** [comment]
Also, you must deploy the bytecode from the npm artifact, and not compile core contracts locally.

**Comment by Bernardchoo** [comment]
ahh. Got it. 
Thanks ! @moodysalem
