### ISSUE TITLE
NFT SVG image

### ISSUE THREAD

**Issue by ewilz** [Uniswap/uniswap-v3-periphery#57]
Complete first iteration of NFT svg images.
**Attributes of Note**: Tokens, Fee, tick range (& liquidity?)

**Comment by ewilz** [comment]
https://github.com/Uniswap/uniswap-v3-periphery/pull/80

**Comment by ewilz** [comment]
https://github.com/Uniswap/uniswap-v3-periphery/pull/112

**Comment by ErikBjare** [comment]
Awesome last minute feature, great job @ewilz! 

I bet this is what @haydenadams was [teasing on Twitter](https://twitter.com/ErikBjare/status/1389647685125382147) ;)
